### ISSUE TITLE
Support for new headless in Chrome

### ISSUE THREAD

**Issue by doekman** [vgalin/html2image#118]
Google Chrome is working on a new headless mode:

https://developer.chrome.com/articles/new-headless/

If nothing is done, the new headless is automatically used end of year, but maybe it is a good thing to look into this?

**Comment by vgalin** [comment]
Thank you for sharing this article. If everything works as announced, it seems to be really good news."
Extensions / Plugins will now work in headless and hopefully there won't be any weird headless-specific behaviour anymore.

**Comment by vgalin** [comment]
Added in release 2.0.4 : https://github.com/vgalin/html2image/releases/tag/2.0.4
