### ISSUE TITLE
Lock of websocket-client

### ISSUE THREAD

**Issue by moiney** [vgalin/html2image#125]
Version 2.0.4 added requirements to the project, but pinned websocket-client to 1.2.3.

Until now, we were using the 1.6.1 version and had no issues. Can you unpin the dependency ?

**Comment by vgalin** [comment]
Hi, thank you for reporting this. The necessary adjustments have been made. Both the master branch of this repo and PyPI are up to date with these changes. 

While I haven't created a new release on GitHub for this update, please let me know if you'd like one, and I'd be happy to accommodate.

**Comment by vgalin** [comment]
Done 👌
