### ISSUE TITLE
Can I use chromium?That can't find chromium

### ISSUE THREAD

**Issue by Starry-Sky-World** [vgalin/html2image#151]

**Comment by vgalin** [comment]
I'll probably need more details to be able to help you, please provide specific error messages and the OS you're using, and the code you use to reproduce this problem.

Chrome, Chromium or even Edge can be used with html2image, but they'll have to be installed on your machine, if html2image can't find them automatically, you'll have to provide it a path, like so :
```
hti = Html2Image(browser_executable='/absolute/path/to/executable'
...
```
