### ISSUE TITLE
An error occurred: the output_file parameter should be a filename and not a path.

### ISSUE THREAD

**Issue by Cryptogevity** [vgalin/html2image#152]
hti = Html2Image(output_path="/tmp/",browser_executable="/opt/chrome/chrome",custom_flags=['--headless',"--disable-gpu","--no-sandbox","--disable-dev-shm-usage"],browser="chromium")
hti.output_path = output_image_folder_path
hti.screenshot(html_str=html, css_str=css, save_as=output_image_path)

And here is the error:
Change the output path by modifying the output_path attribute.

i believe i have specified the output path

**Comment by vgalin** [comment]
Please check if `output_image_path` is a filename and not a path.
