### ISSUE TITLE
Cannot find images

### ISSUE THREAD

**Issue by wangkaihong** [vgalin/html2image#18]
Hi!

I m trying to save a local HTML file as an image but the figures inside are missing. Would you please take a look at this?

`>>> hti.screenshot(html_file='index.html', save_as='out.png')
`
and the file hierarchy looks like this, figures the index.html is referring are stored under images/:

```
drwxr-sr-x. 3 kaiwkh ivc   4096 May 25 11:10 ..
-rw-------. 1 kaiwkh ivc  60152 May 25 11:15 out.png
drwxr-sr-x. 2 kaiwkh ivc  49152 May 25 11:23 images
-rw-r--r--. 1 kaiwkh ivc 317090 May 25 11:23 index.html
drwxr-sr-x. 3 kaiwkh ivc     69 May 25 11:35 .

```
The output image doesn't contain those images:
![image](https://user-images.githubusercontent.com/23068166/119526190-054fd880-bd34-11eb-965a-bd30c89a0b59.png)

Thanks!

**Comment by wangkaihong** [comment]
Thanks for your suggestion but it still doesn't work in that way...

**Comment by wangkaihong** [comment]
Thanks for your help but I think it should be my machine's problem. Much thanks!

**Comment by vgalin** [comment]
All right, no worries. Feel free to come back if you have any issues :)
