### ISSUE TITLE
Cannot save image to other path

### ISSUE THREAD

**Issue by tranmanhhung** [vgalin/html2image#19]
I want save image to other path eg: "/var/www/images/out.jpg"

I receive notice: "ValueError: the output_file parameter should be a filename and not a path."

**Comment by vgalin** [comment]
The name of the outputted files is changed via the `save_as` parameter, while the path is changed via the `output_path` attribute, like so (the following comes from the readme):

---

- **Change the directory to which the screenshots are saved**
```python
hti = Html2Image(output_path='my_screenshot_folder')
```
**OR**
```python
hti.output_path = 'my_screenshot_folder'
```

*N.B. : the output path will be changed for all future screenshots.*

---

Then you can take a screenshot.
