### ISSUE TITLE
Cannot use external assets

### ISSUE THREAD

**Issue by rahulrepal** [vgalin/html2image#23]
Hi...

I am trying to load external fonts from local machine using @font-face but they are not loading. I am stuck with serif.
Please help !!!

**Comment by vgalin** [comment]
Hello, could you provide could you provide a minimal, complete and reproducible example of code of what you are trying to achieve?

**Comment by vgalin** [comment]
I'm closing the issue for inactivity, feel free to reopen it by giving more details.
