### ISSUE TITLE
Full screenshot of a wesbite

### ISSUE THREAD

**Issue by mtvu** [vgalin/html2image#27]
Thanks for putting together this package. Could you give me some guidance on how to take a full screenshot of a website ? The screenshot I got from your example is just the visual part of the website.

**Comment by vgalin** [comment]
Hello, unfortunately, this is something that cannot be done with Chrome headless in command line (what html2image relies on to take screenshots). Even if it allows you to take screenshots of urls, this package is better suited to work with code you have your hands on (so you can control the size of the page typically. 

As this is a common question I'll close the issue and add a disclaimer to the readme.
