### ISSUE TITLE
Hello! library not working on Heroku server

### ISSUE THREAD

**Issue by Mixuigi** [vgalin/html2image#45]
My code: Html2Image().screenshot(html_str=schedule, save_as='red_page.png')
Error: FileNotFoundHError: Could not find a Chrome executable on this machine, please specify it yourself.
This is the simplest line that takes html and saves it as an image. When launched on my computer, everything works perfectly. When running on Heroku, I get this error on the line with the html2Image shown above. It looks like I figured out what the problem is, there is no Chrome on the server. How can I change the path settings for the required components for html2image to work and which components do I need? (I tried to put it on heroku Chrome, the server does not allow to do it)

![Error](https://user-images.githubusercontent.com/72232171/132716779-e05983a8-9a42-4bed-8503-aa7366ac927d.png)

**Comment by vgalin** [comment]
Hello, you may want to install the [Chrome Heroku Buildpack](https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-google-chrome). For more details you can also look at this (similar) issue someone had a few month ago : #39

**Comment by Mixuigi** [comment]
Thanks!)
