### ISSUE TITLE
[Windows] Special character (é, î, ö...) doesn't render correctly for html_str argument.

### ISSUE THREAD

**Issue by monthiller** [vgalin/html2image#5]
Hello,

Thanks for this lib.

Did you do any test with special characters (é, î, ö...) on windows ?
I note that special character doesn't render correctly when the **html is provided as string hti.screenshot(html_str=...)**. (I guess it's because you write the html_str to temp file before calling the browser headless command. Converting the html_str to bytes
should fix the problem.)

Here is simple test that illustrate [test_html2image.zip](https://github.com/vgalin/html2image/files/5643909/test_html2image.zip).

Good job anyway.

**Comment by vgalin** [comment]
Hi,

Thank you for your issue. Being french and using accentuated characters every day, one would thought I had already tried to screenshot some using this package. But I only really used it to screenshot English content, so thanks again for reporting it.

Indeed, special characters such as accentuated ones were not written to the temporary files properly. Converting the string to bytes and writing it to the file fixed this behavior.

You can get the last release (1.1.1) that fixes the problem:
`pip install --upgrade html2image`

I'm closing the issue. Feel free to reopen it if the problem still appears in some cases.
