### ISSUE TITLE
Div above background-image: url('./background.png'); not working

### ISSUE THREAD

**Issue by mpi42** [vgalin/html2image#52]
A Background image as css is not working! any solution? 
thanks

**Comment by vgalin** [comment]
Hello, could you take a look at [this answer](https://github.com/vgalin/html2image/issues/47#issuecomment-940941698) that I gave to an other issue and tell me if it solves your problem?

If that's not the case, I may need more information such as the code that produces this issue.

**Comment by mpi42** [comment]
Thanks that sloved the problem

**Comment by vgalin** [comment]
Thank you for the feedback.
I will now close the issue, if you encounter any problem, feel free to open a new one, or comment again on this one if the problem is directly related.
