### ISSUE TITLE
Verbose should tell user the browser identified / detected 

### ISSUE THREAD

**Issue by tilusnet** [vgalin/html2image#58]
I've been using variants for the parameters `--browser` and `--chrome_path` with no success. The program always does the same thing. It is poorly documented what these values should be. What is `--browser` for?

Switching on the `-v` verbose param only tells the parameters passed by the user but not the _actual_  values computed by the program.

As a user I'd like to know:
* what browser is the tool actually invoking and from where
* what values can the `--browser` parameter accept
* is `chromium` a valid substitute to `chrome`; if so please document it

**Comment by vgalin** [comment]
Thanks for taking the time to open all these issues.

In sort:
- The `--chrome_path` flag has to be fixed on the CLI.
- The `--browser` flag will only be implemented when additional browsers support will be implemented to the package.
- New feature request : display the path of the browser used by the CLI
- Add documentation for the `--chrome_path` as it is missing.

---
`--browser` will be used in the future to select a browser to take screenshots with. At the moment it is not even mentioned in the readme as the only browser supported is Chrome/Chromium.

`--chrome_path` does exist as a parameter. After being parsed, it should be plugged into html2image, but I'm realizing that nothing is done with it... Well that's almost embarrassing, but it does not surprise me as the CLI is still in a work in progress stage and is barely used by anyone yet, not even I.

A temporary workaround would be to use environment variables to indicate to Html2Image which executable path to use. This feature is still untested and undocumented, but you can find [instructions on how to use it here](https://github.com/vgalin/html2image/issues/56#issuecomment-1040502199).

Displaying the path of the browser being used is a good idea. It will be added to the CLI.

Chrome and Chromium are treated the same way, it does not matter to html2image if you are using one or the other as they should behave the same way
