### ISSUE TITLE
Time out setting

### ISSUE THREAD

**Issue by samcheung1** [vgalin/html2image#6]
hello,how can i set time out for screenshot

**Comment by vgalin** [comment]
Hi, is this what you're looking for ?

```python
hti= Html2Image(
    custom_flags=['--timeout=0']
)
hti.screenshot(url="http://example.com", save_as='no_timeout.png')
```

The `custom_flag` parameter lets you specify any flags you want (it is implemented but has yet to be documented).
You can find a list of Chromium flags [here](https://peter.sh/experiments/chromium-command-line-switches/).

**Comment by samcheung1** [comment]
wow! Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vgalin/html2image"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月15日(星期五) 凌晨2:45
收件人:&nbsp;"vgalin/html2image"<html2image@noreply.github.com&gt;;
抄送:&nbsp;"Ghostblack👻"<1123731999@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vgalin/html2image] Time out setting (#6)





 
Hi, is this what you're looking for ?
 hti= Html2Image(     custom_flags=['--timeout=0'] ) hti.screenshot(url="http://example.com", save_as='no_timeout.png')
 
The custom_flag parameter lets you specify any flags you want (it is implemented but has yet to be documented).
 You can find a list of Chromium flags here.

**Comment by samcheung1** [comment]
Hello, i want to ask how can i get html ?

**Comment by samcheung1** [comment]
how can i save html of the page?i try "--save-page-as-mhtml", but it is no use.

**Comment by vgalin** [comment]
The `custom_flag` parameter can't be relied on for everything. In this case, you could do this in many different ways, but I think the easiest one is to change the `temp_path` that Html2Image uses, like so:

```python
hti = Html2Image(temp_path='./html_output')

html = """<h1> An interesting title </h1> This page will be red"""
css = """body {background: red;}"""

hti.screenshot(html_str=html, css_str=css, save_as='red_page.png')
```

This code will take a screenshot that will be saved in the current working directory, but it will also create a folder (again in the current working directory) named `html_output` that contains the html (or any objects) used to generate the screenshot.

Of course in your case, if you want to use timeout **and**  output html to a custom path, you'll have to use the following:
```python
hti = Html2Image(
    custom_flags=['--timeout=0'],
    temp_path='./html_output'
)
```

As your original problem should be resolved, I will now close this issue. If you still have questions, feel free to open a new one, or even use the new `Discussions` tab (found found at the same level as the `Issues` one).

**Comment by samcheung1** [comment]
Thank you for your reply. But, I want to save html from url, can i get it?

**Comment by vgalin** [comment]
Yes, but this has nothing to do with this library. Please take a look at the `requests` library.

**Comment by samcheung1** [comment]
OK! Thank you!

**Comment by cheditx** [comment]
> Hi, is this what you're looking for ?
> 
> ```python
> hti= Html2Image(
>     custom_flags=['--timeout=0']
> )
> hti.screenshot(url="http://example.com", save_as='no_timeout.png')
> ```
> 
> The `custom_flag` parameter lets you specify any flags you want (it is implemented but has yet to be documented). You can find a list of Chromium flags [here](https://peter.sh/experiments/chromium-command-line-switches/).

don't work for me, stop all my code for infinity... no errors nothing!
