### ISSUE TITLE
Capture screenshot is disabled when remote debugging is enabled.

### ISSUE THREAD

**Issue by amandugar** [vgalin/html2image#61]
```python
hti = Html2Image(custom_flags=['--disable-remote-debugging', '--no-sandbox'])  
      
  try: 
      hti.screenshot(html_file='index1.html',
                    save_as='Image-1.jpg',
                    size=(1200, 1200)
                    )

      hti.screenshot(html_file='index2.html',
                      save_as='Image-2.jpg',
                      size=(1200, 1200)
    )
  except:
    print(e)
  
  return ['Image-1.jpg', 'Image-2.jpg']
```

**Comment by amandugar** [comment]
Facing this issue in flask

**Comment by vgalin** [comment]
Hello, could you take a look at the issue #39 , particularly at [this comment](https://github.com/vgalin/html2image/issues/39#issuecomment-927273067) to see if it solves your problem ?

I quote [aurelmegn](https://github.com/aurelmegn):
> `Capture screenshot is disabled when remote debugging is enabled`
> Hey, in case someone is having this error issue with heroku, the chrome build pack enable remote debugging by default, and you need to remove the flag `--remote-debugging-port=9222` in the build pack before using it.
```

**Comment by amandugar** [comment]
> Hello, could you take a look at the issue #39 , particularly at [this comment](https://github.com/vgalin/html2image/issues/39#issuecomment-927273067) to see if it solves your problem ?
> 
> I quote [aurelmegn](https://github.com/aurelmegn):
> 
> > `Capture screenshot is disabled when remote debugging is enabled`
> > Hey, in case someone is having this error issue with heroku, the chrome build pack enable remote debugging by default, and you need to remove the flag `--remote-debugging-port=9222` in the build pack before using it.

Thanks for the quick help it helped me

**Comment by amandugar** [comment]
![image](https://user-images.githubusercontent.com/55328714/155026426-a88098af-baed-4fb8-8b4a-f126fd992d37.png)
This suggests we should add a version as a flag

**Comment by lmanhes** [comment]
> Hello, could you take a look at the issue #39 , particularly at [this comment](https://github.com/vgalin/html2image/issues/39#issuecomment-927273067) to see if it solves your problem ?
> 
> I quote [aurelmegn](https://github.com/aurelmegn):
> 
> > `Capture screenshot is disabled when remote debugging is enabled`
> > Hey, in case someone is having this error issue with heroku, the chrome build pack enable remote debugging by default, and you need to remove the flag `--remote-debugging-port=9222` in the build pack before using it.

Hello, removing the flag `--remote-debugging-port=9222` in the build pack gave me a new error:


<img width="1090" alt="Capture d’écran 2022-03-08 à 07 14 22" src="https://user-images.githubusercontent.com/41304180/157178227-68a1b342-fc20-4837-8ac3-ffe8c96ac696.png">
