### ISSUE TITLE
Problem with sizing

### ISSUE THREAD

**Issue by aramonpa** [vgalin/html2image#63]
Hello guys,

I'm trying to resize an image, my monitor is 1920x1080p but I want to crop the image.

For example: 
`hti.screenshot(html_file = 'index.html', save_as = 'out.jpg', size = (600, 600))`

Where starts to crop the image size parameter? 
My screenshot is getting cropped badly and only is working if I set my full screen resolution.

Kind regards

**Comment by aramonpa** [comment]
Hello again,

I read the documentation again, I think that I missunderstood `size` parameter.
Size parameter specifies the size of the image and not crops the image

Could be possible?

Thanks

**Comment by vgalin** [comment]
Hello, you will have to use an image-processing-dedicated library, such as Pillow, to crop an image, using the [`crop()` method](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.crop) for example.

**Comment by aramonpa** [comment]
Hello vgalin

Yes, supposed that.
I already use `crop()` method of Pillow.

By the way, thanks for your answer, I though that `size` param was for cropping images
