### ISSUE TITLE
Issue using certain flags...

### ISSUE THREAD

**Issue by MarketingPip** [vgalin/html2image#76]
When using virtual-time-budget + background color flag & set to transparent. Program get's stuck in a loop..

There are lot's of other instances and bugs that get it stuck in a loop. 

As well if you set background style sheet to transparent - same thing.

**Comment by vgalin** [comment]
Hello, I've never stumbled on such a problem, could you provide some information about your system (OS + Chrome/Chromium version should do) and a minimal piece of code that would allow to reproduce the issue?

**Comment by vgalin** [comment]
Feel free to reopen the issue if you want to provide more insight.
