### ISSUE TITLE
Non Latin characters displayed incorrectly 

### ISSUE THREAD

**Issue by sokffa** [vgalin/html2image#77]
I'm trying to screenshot an html file, it seems like all Latin characters are displayed incorrectly. It should be an encoding issue, and I don't know how to solve it. 
![image](https://user-images.githubusercontent.com/26129954/194674298-e652b353-ee7d-490f-acae-acc0c977c1ed.png)

**Comment by vgalin** [comment]
Could you provide a minimal working example that will allow to reproduce the issue?

**Comment by vgalin** [comment]
Feel free to reopen the issue if you want to provide more insight.
