### ISSUE TITLE
Convert HTML to image in base64

### ISSUE THREAD

**Issue by DTHerrera** [vgalin/html2image#78]
Hello, there is some way that html2image gets the image in memory or base64?

That is to say that instead of saving the image in a file I generate a string with the image in base64 code

```
from html2image import Html2Image
hti = Html2Image()

imgcode64 = hti.screenshot(html_str=render_template('profile/_riesgoimg.html'))

print(f'Se convirtio a imagen:{imgcode64}')
```

In this case I would expect the imgcode64 variable to have something like the following:

`imgcode64 
= "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALQAAAAoCAYAAABXadAKAAAALnRFWHRDcmVhdGlvbiBUaW1lAHZpZS4gMTkgZmViLiErkJggg=="`

Regards

**Comment by sofiawong** [comment]
Hope this set of code works for you. @DTHerrera 
```
    with open('./src/NER/ner.html') as f:
        hti.screenshot(f.read(), save_as=f'NER.png')
    with open('./src/NER/NER.png', 'rb') as img:
        encodedS = base64.b64encode(img.read())
    imgcode64 = f"data:image/png;base64,{encodedS}"
````

**Comment by DTHerrera** [comment]
Thanks a lot!
