### ISSUE TITLE
Can we use the headless browswer with html2image

### ISSUE THREAD

**Issue by leviethung2103** [vgalin/html2image#79]
Hello, 

I would like to ask you about whether can I use the html2image on the Linux Server without Desktop. I can install the Headless Chrome Browswer on the server. 

Do I need to pass some arguments or flags during the execution ? 

Thank you

**Comment by vgalin** [comment]
Hello, html2image automatically launches Chrome/Chromium in headless mode so it shouldn't be an issue and no additional flags should be necessary.

Except maybe the `no-sandbox` one if you're running as root, so see https://github.com/vgalin/html2image#change-browser-flags on how to change the browser's flags.
