### ISSUE TITLE
Couldn't find a chrome executable. please specify it yourself

### ISSUE THREAD

**Issue by Enigmaderockz** [vgalin/html2image#90]
When this package is highly dependent on chrome executable, it should be written very clearly that where should we mention chrome executable of driver path?

Currently it is not mentioned anywhere. can someone tell me please where can we mention our own chrome binary?

**Comment by Gupta-Anubhav12** [comment]
I'm facing the same issue

**Comment by vgalin** [comment]
The readme specifies the custom arguments that can be used to instantiate the `Html2Image` object, `browser_executable` is one of them. It can be used like so:

```python
# at object instantiation using a parameter
hti = Html2Image(browser_executable='my/custom/path')

# or by changing the value of the corresponding attribute
hti.browser_executable ='my/custom/path'
```
