### ISSUE TITLE
Blank white output

### ISSUE THREAD

**Issue by farzadkb** [vgalin/html2image#92]
Hi,
Can I using html2image on Ubuntu Server 20.4?
I am runnig with custom parameter "hti.browser.flags = ['--no-sandbox']" but output is blank png.
Without --no-sandbox parameter I get this error:
**Running as root without --no-sandbox is not supported. See https://crbug.com/638180.**

**Comment by maphew** [comment]
Try adding a timeout parameter? I was getting partially blank pages sometimes without it. Number is in milliseconds.

    hti = Html2Image()
    hti.browser.flags = ['--virtual-time-budget=50000']

**Comment by IamZiroToxic** [comment]
Its still white for me I even use more than budget like 500000 @maphew
